### ISSUE TITLE
No longer PI macro in opencascade 6.5.3

### ISSUE THREAD

**Issue by equinoxefr** [Heeks/heekscad-old#20]
Hi,

In opencascade 6.5.3, there is no longer PI macro. You must use M_PI instead.

From changelog: Global variables Standard_PI and PI have been eliminated (use macro M_PI instead).

Regards

Pierre

**Comment by equinoxefr** [comment]
Here's a patch for this issue. http://pastebin.com/SYeZAKAq

**Comment by ehb** [comment]
Please close, this changed in commit a061504440eb986b9acc013e1f1e36a840594a13
