### ISSUE TITLE
Missing FindOCE.cmake

### ISSUE THREAD

**Issue by robodan** [Heeks/heekscad-old#4]
cmake .
...
CMake Warning at CMakeLists.txt:26 (find_package):
  Could not find module FindOCE.cmake or a configuration file for package
  OCE.

cmake actually finishes and generates Makefiles; which builds, installs, and runs.  It just looks like a serious problem.

I'm on Fedora 14.  I've tried both 32bit and 64bit.
I have the OpenCASCADE 6.3.0-4.fc14 package installed from fedora.danny.cz.
This happens with both the newest svn and github versions.

**Comment by sliptonic** [comment]
I believe this is now resolved with the new build script.  The new build script removes opencascade as a dependency and builds OCE.  It doesn't uninstall opencascade though.
