### ISSUE TITLE
heekscad compile error

### ISSUE THREAD

**Issue by stefanhristu** [Heeks/heekscad-old#6]
I posted this on the google code site as well, but i guess here it may get more attention.
not sure if I am doing something wrong. installing on fresh ubuntu 11.04 (had to get all the libraries it depends on, which was not intuitive for a newbie) and here is what i see at the end of running make in /heekcad/src (this was done on Aug 3, 2011 at 8:50pm PST):

AF -lTKPLCAF  `wx-config --libs --gl-libs`
HeeksCAD.o: In function `HeeksCADapp::InitializeXMLFunctions()':
/home/stefan/code/heekscad/src/HeeksCAD.cpp:851: undefined reference to`HGear::ReadFromXMLElement(TiXmlElement_)'
HeeksFrame.o: In function `OnSectioningButton':
/home/stefan/code/heekscad/src/HeeksFrame.cpp:930: undefined reference to`HeeksCADapp::SectioningDialog()'
HeeksFrame.o: In function `OnGearButton':
/home/stefan/code/heekscad/src/HeeksFrame.cpp:970: undefined reference to`HGear::HGear()'
../interface/HeeksCADInterface.o: In function `CHeeksCADInterface::ShowSectioningDialog()':
/home/stefan/code/heekscad/src/../interface/HeeksCADInterface.cpp:1785: undefined reference to`HeeksCADapp::SectioningDialog()'
collect2: ld returned 1 exit status
make: *_\* [executable] Error 1
s##@####:~/code/heekscad/src$ git pull
Already up-to-date.

**Comment by sliptonic** [comment]
Take a look at this wiki page: https://github.com/Heeks/heekscad/wiki/Ubuntu-Installation

The build expects things to be in a certain structure.  Cloning with the --recursive flag gets all the the subprojects and checks out the specific versions needed.  I'm closing for now but you should be able to comment if that didn't fix it.
